# Generated by Django 3.0.2 on 2020-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='PRIORITY',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
