# Generated by Django 3.0.2 on 2020-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0003_remove_todomodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[['danger', 'high'], ['success', 'normal'], ['primary', 'low']], default='danger', max_length=100),
            preserve_default=False,
        ),
    ]
