# Generated by Django 3.0.2 on 2020-03-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0004_todomodel_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='priority',
            new_name='priorty',
        ),
    ]
