# Generated by Django 3.0.2 on 2020-03-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0005_auto_20200303_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='priorty',
            new_name='priority',
        ),
    ]
