# Generated by Django 3.0.2 on 2020-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0006_auto_20200303_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[['danger', 'high'], ['success', 'normal'], ['primary', 'low']], max_length=100, null=True),
        ),
    ]
