# Generated by Django 3.0.2 on 2020-03-03 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0007_auto_20200303_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[['danger', 'high'], ['success', 'normal'], ['primary', 'low']], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
