# Generated by Django 3.0.2 on 2020-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0008_auto_20200303_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
