# Generated by Django 3.0.2 on 2020-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0010_auto_20200303_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
