# Generated by Django 3.0.2 on 2020-04-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoorigin', '0013_auto_20200401_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='名前',
            new_name='title',
        ),
    ]
